### ISSUE TITLE
Sidebar Badge

### ISSUE THREAD

**Issue by martincolladodev** [HiDeoo/starlight-heading-badges#5]
### Is your feature request related to a problem?

I'd like to have a badge on the sidebar as well

### Describe the solution you'd like

Add option to add the :badge to the sidebar menu

**Comment by HiDeoo** [comment]
Thanks for the feedback.

[Sidebar badges](https://starlight.astro.build/guides/sidebar/#badges) is a Starlight built-in feature that is already available today.

<img width="327" alt="image" src="https://github.com/user-attachments/assets/72f377a1-0990-4f02-bdc2-f7ba2a5eb9b8">
